title: Musings
description: Things I've observed in Finance
baseurl: "/Musings" # Critical for GitHub project pages
url: "https://NavinNr.github.io"

# This is where the magic happens for your slugs
permalink: /:categories/:title/