title: Musings
description: Things I've observed in Finance
baseurl: "" # Critical for GitHub project pages
url: "https://tdy-i-learned.com"

# This is where the magic happens for your slugs
permalink: /:categories/:title/

plugins:
  - jekyll-paginate
paginate: 12
paginate_path: "/blog/page:num/"